seed_urls:

  # ✅ India Government
  - https://www.india.gov.in/

  # ✅ Tamil Nadu Government
  - https://www.tn.gov.in/

  # ✅ All Indian States (Official Portals)
  - https://www.ap.gov.in/
  - https://www.ts.gov.in/
  - https://www.kerala.gov.in/
  - https://www.karnataka.gov.in/
  - https://www.maharashtra.gov.in/
  - https://www.gujaratindia.com/
  - https://bihar.gov.in/
  - https://rajasthan.gov.in/
  - https://wb.gov.in/
  - https://odisha.gov.in/
  - https://punjab.gov.in/
  - https://haryana.gov.in/
  - https://www.uk.gov.in/
  - https://up.gov.in/
  - https://www.sikkim.gov.in/
  - https://www.meghalaya.gov.in/
  - https://manipur.gov.in/
  - https://nagaland.gov.in/
  - https://www.tripura.gov.in/
  - https://arunachalpradesh.gov.in/
  - https://www.assam.gov.in/
  - https://www.jharkhand.gov.in/
  - https://www.hp.gov.in/
  - https://www.jammuandkashmir.gov.in/
  - https://ladakh.gov.in/

  # ✅ All Indian States (Wikipedia – Single Page)
  - https://en.wikipedia.org/wiki/States_and_union_territories_of_India

  # ✅ All Indian Languages
  - https://en.wikipedia.org/wiki/Languages_of_India
  - https://en.wikipedia.org/wiki/Tamil_language
  - https://en.wikipedia.org/wiki/Hindi
  - https://en.wikipedia.org/wiki/Kannada
  - https://en.wikipedia.org/wiki/Telugu
  - https://en.wikipedia.org/wiki/Malayalam
  - https://en.wikipedia.org/wiki/Bengali_language
  - https://en.wikipedia.org/wiki/Marathi_language
  - https://en.wikipedia.org/wiki/Gujarati_language
  - https://en.wikipedia.org/wiki/Punjabi_language
  - https://en.wikipedia.org/wiki/Odia_language
  - https://en.wikipedia.org/wiki/Assamese_language
  - https://en.wikipedia.org/wiki/Sanskrit

  # ✅ General Knowledge
  - https://en.wikipedia.org/wiki/India
  - https://en.wikipedia.org/wiki/History_of_India
  - https://en.wikipedia.org/wiki/Geography_of_India
  - https://en.wikipedia.org/wiki/Economy_of_India

  # ✅ Tamil History
  - https://en.wikipedia.org/wiki/History_of_Tamil_Nadu
  - https://en.wikipedia.org/wiki/Sangam_period
  - https://en.wikipedia.org/wiki/Chola_dynasty
  - https://en.wikipedia.org/wiki/Chera_dynasty
  - https://en.wikipedia.org/wiki/Pandya_dynasty
  - https://en.wikipedia.org/wiki/Tamil_Kingdoms
  - https://en.wikipedia.org/wiki/Tamil_literature

  # ✅ Tamil Culture
  - https://en.wikipedia.org/wiki/Tamil_culture
  - https://en.wikipedia.org/wiki/Tamil_people
  - https://en.wikipedia.org/wiki/Tamil_festivals
  - https://en.wikipedia.org/wiki/Tamil_cuisine
  - https://en.wikipedia.org/wiki/Tamil_art
  - https://en.wikipedia.org/wiki/Bharatanatyam
  - https://en.wikipedia.org/wiki/Kolam
  - https://en.wikipedia.org/wiki/Jallikattu


# ✅ Chunk settings (good defaults)
chunk:
  target_size: 900
  overlap: 120

# ✅ Retrieval settings
retrieval:
  k: 6
